### PR TITLE
Working container

### PR DESCRIPTION
**Pull request by Zarquan**
Working Docker container with Aladin and TopCat.

### CODE REVIEW

**Comment by bertocco** [comment]
`docker build -f webtop-ubuntu -t ivoadesk .`
is failing with:
Step 17/29 : COPY opt/ivoa/topcat/* ${IVOA_HOME}/topcat
When using COPY with more than one source file, the destination must be a directory and end with a /
Need to fix rows 54, 63, 70 adding / 
After that, the container builds correctly

**Comment by Zarquan** [comment]
Fixed the Dockerfile, adding `'/'` to make it compatible with Docker build.
Seems Podman and Docker aren't totally 100% compatible.

Container builds and runs using both Docker and Podman.

**Comment by Zarquan** [comment]
Added notes on how to build using both Docker and Podman and to publish on both DockerHub and GitHub.

**Comment by bertocco** [comment]
I tried the container. It builds correctly. I run it with:
docker run -d --name=webtop -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -p 3000:3000 <container_id>
keeping information from:
https://github.com/linuxserver/docker-webtop/pkgs/container/webtop
I'm able to access the interface via web with http://localhost:3000/
but i suppose to "be the wrong user" because I see our desktop applications in /opt/ivoa and i'm ableto open them using the full path (I have not the path in $PATH). `whoami` says:
abc
We need instructions on how to use the container, probably.

**Pull request merged**
